<?php

namespace UserStoriesBundle\Repository;

/**
 * AddressRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AddressRepository extends \Doctrine\ORM\EntityRepository {

    public function showAllUserAddress($id) {
        $allUserAddress = $this->getEntityManager()->createQuery(
                "SELECT a "
                . "FROM UserStoriesBundle\Entity\Address a "
                . "INNER JOIN UserStoriesBundle\Entity\User u "
                . "WITH a.address_user=:id"
        );
        $allUserAddress->setParameter('id', $id);
        $query = $allUserAddress->getResult();

        return $query;
    }

}
