<?php

namespace UserStoriesBundle\Repository;

/**
 * EmailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmailRepository extends \Doctrine\ORM\EntityRepository {

    public function showAllUserEmail($id) {
        $allUserEmail = $this->getEntityManager()->createQuery(
                "SELECT e "
                . "FROM UserStoriesBundle\Entity\Email e "
                . "INNER JOIN UserStoriesBundle\Entity\User u "
                . "WITH e.email_user=:id"
        );
        $allUserEmail->setParameter('id', $id);
        $query = $allUserEmail->getResult();

        return $query;
    }

}
