<?php

namespace UserStoriesBundle\Repository;

/**
 * PhoneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhoneRepository extends \Doctrine\ORM\EntityRepository {

    public function showAllUserPhone($id) {
        $allUserPhone = $this->getEntityManager()->createQuery(
                "SELECT p "
                . "FROM UserStoriesBundle\Entity\Phone p "
                . "INNER JOIN UserStoriesBundle\Entity\User u "
                . "WITH p.phone_user=:id"
        );
        $allUserPhone->setParameter('id', $id);
        $query = $allUserPhone->getResult();

        return $query;
    }

}
